### PR TITLE
inheritance mojo pg classes

### PR DESCRIPTION
**Pull request by mche**
### Summary

1. Patching for Inheritance of main classes of Mojo::Pg.
3. And also new attribute $pg->on_connect.
5. And also eval non-blocking callback wrapper.

### CODE REVIEW

**Comment by kraih** [comment]
Afraid i have to give this a :-1: vote, because the patch lacks focus and does a lot of things i don't like.

**Comment by mche** [comment]
Okay, please add possibility of the inheritance by your way.

**Comment by kraih** [comment]
Perhaps this topic should be discussed on IRC or the mailing-list first.

**Comment by mche** [comment]
i had mentioned on http://irclog.perlgeek.de/mojo/2016-06-29#i_12755913

**Comment by mche** [comment]
Ok, @kraih, i'll correct the patch on focus inheritance

**Pull request closed without merging**
